spring.application.name=wisetrip
server.port=8090

# Le dice a Spring donde estan las paginas JSP
spring.mvc.view.prefix=/WEB-INF/vistas/
spring.mvc.view.suffix=.jsp

#geoapify
geoapify.api-key=ebdee7c3955e49f48041b44784b09b1c

#postgres ahora en la BD compartida

#OJO ESTO ES PRIVADO ENTONCES HAY QUE TENER CUIDADO
#queda pendiente preguntarle al profe si al ponerlo en el main todo el mundo tiene acceso.

spring.datasource.url=jdbc:postgresql://ep-twilight-sky-a5jhz43b.us-east-2.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_tB4xMo5JIyPn

spring.datasource.driver-class-name=org.postgresql.Driver

#API de correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=valecor152@gmail.com
spring.mail.password=shrnxapbgrtzdwyb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true