spring.application.name=wisetrip
server.port=8090

# Le dice a Spring donde estan las paginas JSP
spring.mvc.view.prefix=/WEB-INF/vistas/
spring.mvc.view.suffix=.jsp
# api geoapify
geoapify.api.key = ebdee7c3955e49f48041b44784b09b1c; 

